# Generated by Django 2.2.2 on 2019-06-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.TextField()),
                ('configuration', models.TextField()),
                ('description', models.TextField()),
                ('values', models.TextField()),
                ('default', models.TextField()),
            ],
            options={
                'verbose_name': 'ConfigurationTable',
                'verbose_name_plural': 'ConfigurationTables',
            },
        ),
    ]
